### ISSUE TITLE
Injected provider can't be used if not provided as an explicit option by client

### ISSUE THREAD

**Issue by mholtzman** [blocknative/onboard#600]
#583  introduced support for being able to use arbitrary injected providers. However it seems like any dapp that doesn't explicitly provide 'detectedwallet' in the list of wallet names can create a situation where the injected provider is detected by the library but can't be selected. 

Here's an example using injected Frame:

![image](https://user-images.githubusercontent.com/3717135/124518060-81b5ec80-ddb3-11eb-97c1-d10d568a42b0.png)
![image](https://user-images.githubusercontent.com/3717135/124518040-795db180-ddb3-11eb-9a43-c4d387229235.png)

Notice that Frame doesn't appear as an option but other options refer to the fact that Frame is being used so the result is that I can't use the dapp.

It seems in general that forcing clients to provide the 'detectedwallet' option kind of defeats the purpose of being able to inject a provider in the first place. I think if the user or dapp goes to the trouble of injecting a wallet, they intend to use it at some point and it feels antithetical to the idea to put the onus on the dapp to opt in to these.

**Comment by taylorjdawson** [comment]
@mholtzman Thanks for pointing this out, I think this is a bug as the injected wallet is included and should display by default if it detects that a wallet is injected. We'll look at this next week. If you discover any new information in the meantime please share it here, thanks!

**Comment by taylorjdawson** [comment]
@mholtzman The idea is actually for the developer to get to decide whether or not they want to use this feature. This is why you must put `{ walletName: 'detectedwallet'`.

**Comment by mholtzman** [comment]
thanks @taylorjdawson for taking a look at this.

What I'm striving for here is to promote compatibility with EIP-1193 as it really embraces the spirit of decentralization and benefits everyone in the ecosystem. Needing to opt-in to compatibility feels a little counterproductive as it becomes exclusionary to providers that haven't explicitly been recognized by individual dapps and forces wallets to do things like add the isMetaMask flag to make their providers work. 

  If a user is injecting their own provider they clearly would like to use it and I think not supporting that by default erects unnecessary barriers to entry for both users of onboard.js and the Ethereum ecosystem in general. Providing out of the box support for any EIP-1193 provider will go a long way towards promoting healthy standards within the space.

**Comment by techgangboss** [comment]
Hi @mholtzman , we believe giving the optionality to the developer is more aligned with the spirit of the ecosystem if the developer has gone the route of picking the wallets they would like to support. If the developer uses the default wallet list it is already there by default. Either way since it is an open-source project the integrating developer holds the ultimate control on how the injected provider should become available.

**Comment by jmhickman** [comment]
So I'm a Frame user affected by this on zapper.fi. I'm trying to understand this, as I'm not a javascript developer; is the default behavior of onboard.js to support any wallet provider following 1193?
If so, what are some reasons an application would change this default?

**Comment by androolloyd** [comment]
Hi, 

As a developer and Frame user I am curious why this would be the case, I think a more logical approach here is to have developers opt out of supporting the injected providers vs opting in.

1193 Is a standard for injected providers and making it available by default greatly improves the UX for all and meets expectations that come with leveraging these providers who support 1193, as well as ensuring developers have a way to drop support for it should they not be able to.

**Comment by floating** [comment]
Hey all! 

I agree, the issue here is not if the developer should have this level of control, it's with how the current configuration for it is designed. The way it's designed now made it so any dapp that has not been using the default wallet list is now unintentionally breaking the provider specification by upgrading to the latest version.

As the majority of developers would choose to support EIP-1193 if presented with the choice, it would be much more in line with the ecosystem to enable compatibility with the provider specification by default (without needing configuration to keep it on) and then provide an option for the developer if they wish to disable it.

**Comment by techgangboss** [comment]
@floating @androolloyd  To be clear, the current configuration supports it by default and the developer does not have to do anything; the current implementation is on the opt-out approach. What is at question here is if the developer goes the _custom_ route, then it is not forced to be on there. However we do pay close attention to our community and we hear your request here, and we are looking at an implementation to solve this issue. Please stand by and I will provide an update.

**Comment by taylorjdawson** [comment]
We'll include this in the next release (v1.31.0) 🙂

**Comment by jmhickman** [comment]
Excellent!

**Comment by floating** [comment]
@taylorjdawson @techgangboss Thanks for your help and responsiveness with this issue!

**Comment by techgangboss** [comment]
@floating @jmhickman @androolloyd We have included the changes with the latest release `v1.31.0` . We will be closing this issue.

**Comment by taylorjdawson** [comment]
Fixed in #625 release in #627.

**Comment by floating** [comment]
@taylorjdawson @techgangboss Has there been a regression here? We are still frequently having our users report this as an issue. For example it seems Gnosis Safe (using `"bnc-onboard": "~1.34.2"`) still results in users getting stuck with this message but still unable to choose the injected provider. 

<img width="615" alt="Screen Shot 2021-09-26 at 1 04 33 PM" src="https://user-images.githubusercontent.com/598504/134817164-f5753a58-2d3a-4ff6-bb4b-d8a191a611c8.png">

**Comment by taylorjdawson** [comment]
@floating Thanks for bring this back up! I think the focus of this issue was to make `detectedwallet` not optional which was addressed but another issue remained where wallets supported by onboard are excluded from being injected. I am going to create a separate issue for this and will update: #697.
